sonata_admin:
    title:      Mid-Norfolk Railway Portal
    title_logo: bundles/app/img/apple-touch-icon.png
    
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display

    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -   
                position: center
                type: sonata.timeline.block.timeline
                settings: 
                    context: SONATA_ADMIN
                    max_per_page: 25
            
            -
                position: right
                type: sonata.block.service.rss
                settings:
                    title: Sonata Project's Feeds
                    url: http://sonata-project.org/blog/archive.rss
            
        groups:
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="halflings-icon white user"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    

    assets:
        stylesheets: ~
        javascripts: ~
